    export const data = [
        {
            id: 1,
            code: "BM0001",
            house: "photos/house/house1.jpeg",
            title: "Willow Creek Manor",
            location: "Grantham Street, D08 W8HD, Dublin - Ireland",
            description: "This timeless estate offers a glimpse into luxury Victorian design with intricate woodwork, a sweeping wrap-around porch, and rich mahogany interiors.",
            moreInfo: "Step into the grand foyer and enjoy chandeliers, a marble fireplace, and rooms adorned with antique finishes. Perfect for elegant entertaining, this home boasts a parlor, library, and a secluded garden with stone pathways.",
            type: "buy",
            price: "€110,100",
            bath: "1",
            bed: 1,
            sqm: 110,
            kitchenPhoto: "photos/kitchen/kitchen1.jpg",
            bathPhoto: "photos/bath/bath1.jpg",
            bedPhoto: "photos/bed/bed1.jpg",
            roomPhoto: "photos/room/room1.jpg"
        },
        {
            id: 2,
            code: "BM0002",
            house: "photos/house/house2.jpeg",
            title: "The Skylight Chalet",
            location: "Mountain View Road, Aspen, Colorado",
            description: "A cozy mountain retreat with expansive skylights that fill the living areas with natural light.",
            moreInfo: "Set against a breathtaking mountain backdrop, this chalet invites relaxation with high, exposed wooden beams and cozy stone fireplaces. Expansive skylights and floor-to-ceiling windows frame nature views, while heated floors and soft, earthy tones create a sense of warmth.",
            type: "rent",
            price: "€200/month",
            bath: 2,
            bed: 3,
            sqm: 140,
            kitchenPhoto: "photos/kitchen/kitchen2.jpg",
            bathPhoto: "photos/bath/bath2.jpg",
            bedPhoto: "photos/bed/bed2.jpg",
            roomPhoto: "photos/room/room2.jpg"
        },
        {
            id: 3,
            code: "BM0003",
            house: "photos/house/house3.jpeg",
            title: "Lakeview Lodge",
            location: "Lakefront Drive, Lake Tahoe",
            description: "An elegant cabin by the lake with a sprawling deck, panoramic windows, and a stone chimney.",
            moreInfo: "Perfectly situated for lakeside living, this lodge combines rustic charm with modern luxury. A vast deck offers panoramic lake views, while the spacious great room features vaulted pine ceilings, exposed beams, and a stone fireplace.",
            type: "buy",
            price: "€450,000",
            bath: 3,
            bed: 4,
            sqm: 200,
            kitchenPhoto: "photos/kitchen/kitchen3.jpg",
            bathPhoto: "photos/bath/bath3.jpg",
            bedPhoto: "photos/bed/bed3.jpg",
            roomPhoto: "photos/room/room3.jpg"
        },
        {
            id: 4,
            code: "BM0004",
            house: "photos/house/house4.jpeg",
            title: "Horizon Cottage",
            location: "Countryside Lane, Norfolk, England",
            description: "A charming countryside home with an English garden, white picket fence, and ivy-covered brick walls.",
            moreInfo: "This enchanting cottage offers classic countryside appeal with ivy-draped brick walls, a picturesque white picket fence, and an expertly landscaped English garden. The interior is decorated with vintage furnishings, cozy reading nooks, and an inviting kitchen with farmhouse details.",
            type: "rent",
            price: "€150/month",
            bath: 2,
            bed: 2,
            sqm: 120,
            kitchenPhoto: "photos/kitchen/kitchen4.jpg",
            bathPhoto: "photos/bath/bath4.jpg",
            bedPhoto: "photos/bed/bed4.jpg",
            roomPhoto: "photos/room/room4.jpg"
        },
        {
            id: 5,
            code: "BM0005",
            house: "photos/house/house5.jpeg",
            title: "The Modern Muse",
            location: "Cityscape Avenue, Los Angeles, CA",
            description: "A sleek, contemporary home with minimalist architecture, high ceilings, and floor-to-ceiling glass walls.",
            moreInfo: "Sophisticated and sleek, The Modern Muse epitomizes contemporary design with clean lines, an open floor plan, and abundant natural light. Floor-to-ceiling glass seamlessly integrates indoor and outdoor spaces, leading to an infinity pool with serene views.",
            type: "buy",
            price: "€1,200,000",
            bath: 4,
            bed: 5,
            sqm: 320,
            kitchenPhoto: "photos/kitchen/kitchen5.jpg",
            bathPhoto: "photos/bath/bath5.jpg",
            bedPhoto: "photos/bed/bed5.jpg",
            roomPhoto: "photos/room/room5.jpg"
        },
        {
            id: 6,
            code: "BM0006",
            house: "photos/house/house6.jpeg",
            title: "Seaside Haven",
            location: "Ocean Breeze Lane, Malibu, CA",
            description: "A beach house with a pastel exterior, large veranda, and sweeping ocean views.",
            moreInfo: "Embrace coastal living in this pastel-colored beach house featuring expansive ocean views and an airy, open floor plan. With a large veranda perfect for sunset dinners, a sunroom for lounging, and nautical decor throughout.",
            type: "rent",
            price: "€300/month",
            bath: 2,
            bed: 3,
            sqm: 160,
            kitchenPhoto: "photos/kitchen/kitchen6.jpg",
            bathPhoto: "photos/bath/bath6.jpg",
            bedPhoto: "photos/bed/bed6.jpg",
            roomPhoto: "photos/room/room6.jpg"
        },
        {
            id: 7,
            code: "BM0007",
            house: "photos/house/house7.jpeg",
            title: "The Treehouse Retreat",
            location: "Forest Lane, Oregon",
            description: "An elevated home nestled among tree canopies, with large glass windows offering scenic forest views.",
            moreInfo: "Escape to this unique, eco-friendly retreat set high among the treetops. Floor-to-ceiling windows bring in panoramic forest views, while sustainable materials and a rooftop garden make this a green getaway.",
            type: "buy",
            price: "€600,000",
            bath: 2,
            bed: 3,
            sqm: 150,
            kitchenPhoto: "photos/kitchen/kitchen7.jpg",
            bathPhoto: "photos/bath/bath7.jpg",
            bedPhoto: "photos/bed/bed7.jpg",
            roomPhoto: "photos/room/room7.jpg"
        },
        {
            id: 8,
            code: "BM0008",
            house: "photos/house/house8.jpeg",
            title: "Aurora Villa",
            location: "Northern Lights Avenue, Stockholm, Sweden",
            description: "A luxurious Scandinavian-inspired home with white-washed walls, expansive windows, and open spaces.",
            moreInfo: "Inspired by Scandinavian design, Aurora Villa combines minimalist elegance with warmth and coziness. White-washed walls, natural wood finishes, and expansive glass windows create an open and inviting space that blends with the landscape.",
            type: "rent",
            price: "€450/month",
            bath: 3,
            bed: 4,
            sqm: 250,
            kitchenPhoto: "photos/kitchen/kitchen8.jpg",
            bathPhoto: "photos/bath/bath8.jpg",
            bedPhoto: "photos/bed/bed8.jpg",
            roomPhoto: "photos/room/room8.jpg"
        },
        {
            id: 9,
            code: "BM0009",
            house: "/photos/house/house9.jpeg",
            title: "The Heritage Homestead",
            location: "Farmhouse Road, Kentucky",
            description: "An old farmhouse restored to preserve its charm, with exposed brick, wood-beamed ceilings, and vintage decor.",
            moreInfo: "This restored farmhouse preserves its rustic charm while offering modern comforts. Featuring exposed brick walls, wood-beamed ceilings, and vintage decor, The Heritage Homestead is a blend of historic charm and cozy appeal.",
            type: "buy",
            price: "€350,000",
            bath: 2,
            bed: 3,
            sqm: 180,
            kitchenPhoto: "photos/kitchen/kitchen9.jpg",
            bathPhoto: "photos/bath/bath9.jpg",
            bedPhoto: "photos/bed/bed9.jpg",
            roomPhoto: "photos/room/room9.jpg"
        },
        {
            id: 10,
            code: "BM0010",
            house: "photos/house/house10.jpeg",
            title: "Echo Ridge Estate",
            location: "Hillside Drive, Napa Valley, CA",
            description: "A sprawling estate with a mix of modern and rustic styles, set against a backdrop of rolling hills.",
            moreInfo: "Echo Ridge Estate offers a stunning blend of modern comfort and rustic charm. Set against rolling hills, the property features an open-plan living space, a custom wine cellar, and a grand patio with a fire pit.",
            type: "rent",
            price: "€750/month",
            bath: 5,
            bed: 6,
            sqm: 450,
            kitchenPhoto: "photos/kitchen/kitchen10.jpg",
            bathPhoto: "photos/bath/bath10.jpg",
            bedPhoto: "photos/bed/bed10.jpg",
            roomPhoto: "photos/room/room10.jpg"
        }
    ];